"""
tensor_net.py — Waveform-driven tensor generation and resonance neural network.

The UMO signal Φ(t) = sin(τ·t) × cos(ρ·t) × (1−ε) is sampled on a 2D grid:

  rows  → time axis          (t  = row_idx × dt)
  cols  → harmonic axis      (ρ′ = ρ × (col_idx + 1))

This gives a deterministic weight matrix whose structure is completely
determined by (trust, entropy, resonance) — no random seed, no hidden state.

A ResonanceNet is a feedforward network whose every weight matrix is
generated this way. The trust level governs amplitude (weight magnitude),
entropy damps all weights uniformly, resonance sets the frequency structure
across the hidden-layer harmonic axis.

Forward pass uses tanh activation (bounded, compatible with the WORM entropy gate).
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Sequence

import numpy as np

from .umo import Umo


# ---------------------------------------------------------------------------
# Tensor generation
# ---------------------------------------------------------------------------

def waveform_tensor(
    umo:       Umo,
    shape:     tuple[int, int],
    t_offset:  float = 0.0,
    dt:        float = 0.15,
) -> np.ndarray:
    """
    Sample the oscillator on a (rows × cols) grid to produce a weight matrix.

    Each column uses a harmonic of the resonance frequency:
        Φ[i, j] = sin(τ · (t_offset + i·dt)) · cos(ρ·(j+1) · (t_offset + i·dt)) · (1−ε)

    Parameters
    ----------
    umo       : oscillator state
    shape     : (rows, cols)
    t_offset  : time base for this layer (different layers offset to vary structure)
    dt        : time step between rows
    """
    rows, cols = shape
    W = np.empty((rows, cols), dtype=np.float32)
    for i in range(rows):
        t = t_offset + i * dt
        for j in range(cols):
            harmonic_rho = umo.resonance * (j + 1)
            W[i, j] = (
                math.sin(umo.trust * t)
                * math.cos(harmonic_rho * t)
                * (1.0 - umo.entropy)
            )
    return W


def waveform_bias(
    umo:      Umo,
    size:     int,
    t_offset: float = 0.0,
) -> np.ndarray:
    """Sample the oscillator at evenly-spaced points to produce a bias vector."""
    b = np.empty(size, dtype=np.float32)
    for j in range(size):
        t = t_offset + j * (math.pi / max(size, 1))
        b[j] = umo.signal(t) * 0.1   # small bias
    return b


# ---------------------------------------------------------------------------
# ResonanceNet
# ---------------------------------------------------------------------------

@dataclass
class LayerSpec:
    in_dim:  int
    out_dim: int
    weights: np.ndarray = field(repr=False)
    bias:    np.ndarray = field(repr=False)


@dataclass
class ResonanceNet:
    """
    Feedforward neural network whose weights are generated by the UMO oscillator.

    Architecture is fully determined by (τ, ε, ρ) and layer_sizes.
    No random initialization — the oscillator IS the initializer.

    The entropy gate enforces ε < 0.21 before generation; an incoherent
    oscillator produces a degenerate (near-zero) weight network.
    """
    umo:    Umo
    layers: list[LayerSpec]

    @classmethod
    def build(
        cls,
        umo:          Umo,
        layer_sizes:  Sequence[int],
        dt:           float = 0.15,
        layer_t_gap:  float = math.pi,   # time gap between layers
    ) -> "ResonanceNet":
        """
        Construct a ResonanceNet from an oscillator state and a list of layer widths.

        layer_sizes = [input_dim, hidden1, hidden2, ..., output_dim]
        """
        if not umo.coherent():
            # Incoherent field: all-zero weights (entropy collapsed the network)
            layers = [
                LayerSpec(
                    in_dim  = layer_sizes[i],
                    out_dim = layer_sizes[i + 1],
                    weights = np.zeros((layer_sizes[i], layer_sizes[i + 1]), dtype=np.float32),
                    bias    = np.zeros(layer_sizes[i + 1], dtype=np.float32),
                )
                for i in range(len(layer_sizes) - 1)
            ]
        else:
            layers = []
            for idx in range(len(layer_sizes) - 1):
                in_dim  = layer_sizes[idx]
                out_dim = layer_sizes[idx + 1]
                t_off   = idx * layer_t_gap
                W = waveform_tensor(umo, (in_dim, out_dim), t_offset=t_off, dt=dt)
                b = waveform_bias(umo, out_dim, t_offset=t_off + in_dim * dt)
                layers.append(LayerSpec(in_dim=in_dim, out_dim=out_dim, weights=W, bias=b))

        return cls(umo=umo, layers=layers)

    # ------------------------------------------------------------------
    # Forward pass
    # ------------------------------------------------------------------

    def forward(self, x: np.ndarray) -> np.ndarray:
        """
        Run a forward pass. Uses tanh activation on hidden layers, linear output.
        x shape: (batch, input_dim) or (input_dim,)
        """
        h = x.astype(np.float32)
        for i, layer in enumerate(self.layers):
            h = h @ layer.weights + layer.bias
            if i < len(self.layers) - 1:
                h = np.tanh(h)
        return h

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------

    def summary(self) -> str:
        lines = [
            f"ResonanceNet  τ={self.umo.trust:.3f}  ε={self.umo.entropy:.3f}  ρ={self.umo.resonance:.3f}",
            f"  coherent: {'YES ☉' if self.umo.coherent() else 'NO ⛔'}",
            f"  layers  : {len(self.layers)}",
        ]
        total = 0
        for i, l in enumerate(self.layers):
            params = l.weights.size + l.bias.size
            total += params
            lines.append(
                f"  [{i}] ({l.in_dim} → {l.out_dim})  "
                f"W={l.weights.shape}  ‖W‖={np.linalg.norm(l.weights):.3f}  params={params}"
            )
        lines.append(f"  total params: {total}")
        return "\n".join(lines)

    def weight_tensor(self) -> np.ndarray:
        """Stack all weight matrices into a single 3-D tensor [layer, in, out]."""
        # Pad to uniform shape for stacking
        max_in  = max(l.in_dim  for l in self.layers)
        max_out = max(l.out_dim for l in self.layers)
        stacked = np.zeros((len(self.layers), max_in, max_out), dtype=np.float32)
        for i, l in enumerate(self.layers):
            stacked[i, :l.in_dim, :l.out_dim] = l.weights
        return stacked
