"""
resonance_attention.py — SUBLEQ Branch Attention with Resonance-generated projections.

Wires the Resonance ISA oscillator (UMO) into the SUBLEQ attention mechanism:

  Standard SBA:
    W_q, W_k, W_v = nn.Linear (learned)
    scores        = SUBLEQ_compete(Q, K)
    attn          = scores @ V

  Resonance SBA (this module):
    W_q, W_k, W_v = waveform_tensor(umo, shape)  ← oscillator-generated, no random seed
    scores        = SUBLEQ_compete(Q, K)          ← same binary competition
    opcode        = plugboard.route(band)         ← BRANCH taken → Abjad opcode
    attn          = scores @ V

Entropy gate (mirrors sba/kernel.py AGIKernelState invariant):
  UMO.coherent() requires ε < 0.21 and τ > 0.5
  Incoherent field → zero weight projections → SILENCE (no attention output)

The two entropy constants are the same invariant:
  kernel.py    : entropy_budget ≤ 0.20
  umo.coherent : ε < 0.21
  → coherent field is exactly within the kernel's entropy budget.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Optional

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from .resonance.umo import Umo
from .resonance.tensor_net import waveform_tensor, waveform_bias, ResonanceNet
from .resonance.plugboard import Plugboard, ABJAD_OPS
from .resonance.bridge import DrainInvariants, invariants_to_umo
from .subleq_attention import SUBLEQCompetition

P_GOLD = 18446744069414584321  # SNARK prime (mirrors kernel.py)


# ---------------------------------------------------------------------------
# Oscillator-generated linear projection
# ---------------------------------------------------------------------------

class WaveformLinear(nn.Module):
    """
    Drop-in replacement for nn.Linear whose weight matrix is generated by
    the UMO oscillator rather than random initialisation.

    If the UMO field is incoherent (ε >= 0.21 or τ <= 0.5), weight is all-zero
    and the projection outputs silence — matching the kernel entropy gate.
    """

    def __init__(self, umo: Umo, in_features: int, out_features: int, t_offset: float = 0.0):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.umo = umo

        if umo.coherent():
            W_np = waveform_tensor(umo, (in_features, out_features), t_offset=t_offset)
            b_np = waveform_bias(umo, out_features, t_offset=t_offset)
        else:
            W_np = np.zeros((in_features, out_features), dtype=np.float32)
            b_np = np.zeros(out_features, dtype=np.float32)

        # Register as non-learnable buffers (oscillator owns these weights)
        self.register_buffer("weight", torch.from_numpy(W_np.T))  # (out, in)
        self.register_buffer("bias",   torch.from_numpy(b_np))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return F.linear(x, self.weight, self.bias)

    def refresh(self, umo: Umo, t_offset: float = 0.0):
        """Re-generate weights from a new UMO state (e.g. after drain update)."""
        self.umo = umo
        if umo.coherent():
            W_np = waveform_tensor(umo, (self.in_features, self.out_features), t_offset=t_offset)
            b_np = waveform_bias(umo, self.out_features, t_offset=t_offset)
        else:
            W_np = np.zeros((self.in_features, self.out_features), dtype=np.float32)
            b_np = np.zeros(self.out_features, dtype=np.float32)
        self.weight.copy_(torch.from_numpy(W_np.T))
        self.bias.copy_(torch.from_numpy(b_np))


# ---------------------------------------------------------------------------
# Resonance SUBLEQ Attention
# ---------------------------------------------------------------------------

@dataclass
class ResonanceAttentionOutput:
    output:      torch.Tensor        # (batch, seq, dim)
    attn_mask:   torch.Tensor        # (batch, heads, seq, seq) binary
    opcode:      str                 # Abjad opcode from plugboard routing
    coherent:    bool                # UMO field coherent?
    entropy:     float               # UMO ε
    waveform:    str                 # UMO waveform snapshot


class ResonanceSUBLEQAttention(nn.Module):
    """
    SUBLEQ Branch Attention with oscillator-generated Q/K/V projections.

    The Q, K, V weight matrices are NOT learned — they are generated by the
    UMO waveform_tensor from (τ, ε, ρ). This makes attention weights a direct
    function of the drain pipeline's residual complexity and entropy.

    On every forward pass, the plugboard routes the dominant signal band to
    an Abjad opcode. When SUBLEQ branches (diff < 0), the opcode is BRANCH;
    when it falls through, the opcode reflects the current band's routing.

    Architecture:
      DrainInvariants → UMO(τ, ε, ρ) → WaveformLinear(W_q, W_k, W_v)
                                      → SUBLEQCompetition
                                      → Plugboard routing → opcode
                                      → attn_mask @ V → W_o → output
    """

    def __init__(
        self,
        umo:       Umo,
        dim:       int,
        num_heads: int  = 8,
    ):
        super().__init__()
        assert dim % num_heads == 0

        self.dim       = dim
        self.num_heads = num_heads
        self.head_dim  = dim // num_heads
        self.umo       = umo

        # Oscillator-generated projections (one t_offset per projection = varied structure)
        self.W_q = WaveformLinear(umo, dim, dim, t_offset=0.0)
        self.W_k = WaveformLinear(umo, dim, dim, t_offset=math.pi)
        self.W_v = WaveformLinear(umo, dim, dim, t_offset=2 * math.pi)
        self.W_o = WaveformLinear(umo, dim, dim, t_offset=3 * math.pi)

        self.competition = SUBLEQCompetition(self.head_dim)
        self.plugboard   = Plugboard.build(umo)

    # ------------------------------------------------------------------

    def update_umo(self, umo: Umo):
        """Re-derive all projections from new drain invariants."""
        self.umo = umo
        self.W_q.refresh(umo, t_offset=0.0)
        self.W_k.refresh(umo, t_offset=math.pi)
        self.W_v.refresh(umo, t_offset=2 * math.pi)
        self.W_o.refresh(umo, t_offset=3 * math.pi)
        self.plugboard = Plugboard.build(umo)

    def update_from_invariants(self, inv: DrainInvariants):
        """Convenience: map drain pipeline output → UMO → refresh."""
        self.update_umo(invariants_to_umo(inv))

    # ------------------------------------------------------------------

    def forward(
        self,
        x:           torch.Tensor,
        mask:        Optional[torch.Tensor] = None,
    ) -> ResonanceAttentionOutput:
        """
        Args:
            x    : (batch, seq_len, dim)
            mask : (batch, seq_len) bool padding mask, optional
        Returns:
            ResonanceAttentionOutput
        """
        B, T, D = x.shape
        H, Hd   = self.num_heads, self.head_dim

        # Entropy gate: incoherent field → zero output (SILENCE)
        if not self.umo.coherent():
            silence = torch.zeros_like(x)
            dummy   = torch.zeros(B, H, T, T)
            return ResonanceAttentionOutput(
                output    = silence,
                attn_mask = dummy,
                opcode    = "HALT",
                coherent  = False,
                entropy   = self.umo.entropy,
                waveform  = self.umo.waveform(),
            )

        # Project Q, K, V
        Q = self.W_q(x).view(B, T, H, Hd).transpose(1, 2)  # (B, H, T, Hd)
        K = self.W_k(x).view(B, T, H, Hd).transpose(1, 2)
        V = self.W_v(x).view(B, T, H, Hd).transpose(1, 2)

        # SUBLEQ competition → binary attention mask
        attn_mask = self.competition(Q, K)  # (B, H, T, T)

        if mask is not None:
            attn_mask = attn_mask * mask.unsqueeze(1).unsqueeze(2).float()

        # Attended values
        out = torch.matmul(attn_mask, V)               # (B, H, T, Hd)
        out = out.transpose(1, 2).contiguous().view(B, T, D)
        out = self.W_o(out)

        # Plugboard: route current waveform sample → opcode
        sample  = self.umo.signal(0.0)
        opcode  = self.plugboard.route(sample)

        return ResonanceAttentionOutput(
            output    = out,
            attn_mask = attn_mask,
            opcode    = opcode,
            coherent  = True,
            entropy   = self.umo.entropy,
            waveform  = self.umo.waveform(),
        )


# ---------------------------------------------------------------------------
# Factory helpers
# ---------------------------------------------------------------------------

def from_drain_invariants(
    inv:       DrainInvariants,
    dim:       int,
    num_heads: int = 8,
) -> ResonanceSUBLEQAttention:
    """Build a ResonanceSUBLEQAttention directly from drain pipeline output."""
    umo = invariants_to_umo(inv)
    return ResonanceSUBLEQAttention(umo=umo, dim=dim, num_heads=num_heads)


def demo_attention(dim: int = 64, num_heads: int = 4) -> ResonanceSUBLEQAttention:
    """Construct a demo instance with synthetic invariants (coherent field)."""
    umo = Umo(trust=0.85, entropy=0.08, resonance=0.72)
    return ResonanceSUBLEQAttention(umo=umo, dim=dim, num_heads=num_heads)
